name: Release Label Checker

on:
  pull_request:
    types: [labeled, unlabeled]
  pull_request_review:
    types: [submitted]
jobs:
  commented-auto-labeler:
    permissions:
      contents: write
      pull-requests: write
      repository-projects: read
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
      NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check approval count
        id: approval-check
        run: |
          APPROVALS=$(gh pr view ${{ github.event.pull_request.number }} --json reviews --jq '[.reviews[] | select(.state=="APPROVED")] | length')
          echo "approve_count=$APPROVALS" >> $GITHUB_OUTPUT
          echo "approvals=$APPROVALS"
      - name: Check labels
        id: check-label
        if: steps.approval-check.outputs.approvals >= 2
        run: |
          REQUIRED_LABELS=(
            "feature"
            "enhancement"
            "fix"
            "bugfix"
            "bug"
            "accessibility"
            "test"
            "refactoring"
            "other"
          )
          PR_LABELS=$(gh pr view ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --json labels --jq '.labels[].name')
          echo "pr_labels=${PR_LABELS}" >> $GITHUB_OUTPUT

          # リリースタイプのラベルが1つでも付いているか確認
          LABEL_FOUND=false
          for label in "${REQUIRED_LABELS[@]}"; do
            if echo "$PR_LABELS" | grep -q "$label"; then
              LABEL_FOUND=true
              break
            fi
          done

          echo "label_found=$LABEL_FOUND" >> $GITHUB_OUTPUT
          echo "label_found=$LABEL_FOUND"
      - name: Comment if no label
        if: steps.approval-check.outputs.approvals >= 2 && steps.check-label.outputs.label_found == 'false'
        run: |
          gh pr comment $NUMBER --body-file ".github/release-type.md" --repo ${{ github.repository }}
          exit 1
  ignore-release-label:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-24.04
    if: |
      !github.event.pull_request.draft &&
      github.event.pull_request.state == 'open' &&
      github.event.pull_request.base.ref != 'staging'
    steps:
      - name: Add ignore release label
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh pr edit $NUMBER --add-label "release_ignore" --repo ${{ github.repository }}
