name: Release Drafter

on:
  push:
    branches:
      - main
      - release-note
jobs:
  create_release_note:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-24.04
    steps:
      - name: Get current date
        id: date
        run: |
          export TZ=JST-9
          echo "name=$(date +"%Y-%m-%d_%H:%M")" >> $GITHUB_OUTPUT
          echo "tag=$(date +"%Y%m%d%H%M")" >> $GITHUB_OUTPUT
      - uses: release-drafter/release-drafter@v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: main
          config-name: release-type.yml
          tag: ${{ steps.date.outputs.tag }}
          name: ${{ steps.date.outputs.name }}
