name: Release Drafter

on:
  push:
    branches:
      - main
jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: |
          # JSTの日付を取得
          export TZ=JST-9
          DATETIME=$(date +"%Y%m%d %H:%M")
          echo "date=$DATETIME" >> $GITHUB_OUTPUT
      - uses: release-drafter/release-drafter@v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: develop
          config-name: release-type.yml
          tag: "${{ steps.date.outputs.date }}"
          name: ${{ steps.date.outputs.date }}
